@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ru.job4j.tracker.StartUI#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "ru.job4j.tracker.StartUI"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_101295923 { 
   	label=job4j
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2048152707 { 
   	label=tracker
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1000887473 { 
   	label=EditItemAction
	labeljust=l
	fillcolor=white
	style=filled
   
   EditItemAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="EditItemAction

null"
	fontcolor=darkgreen
];

EditItemAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="EditItemAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_155940494 { 
   	label=ShowAllItemsAction
	labeljust=l
	fillcolor=white
	style=filled
   
   ShowAllItemsAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="ShowAllItemsAction

null"
	fontcolor=darkgreen
];

ShowAllItemsAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="ShowAllItemsAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1578201028 { 
   	label=Tracker
	labeljust=l
	fillcolor=white
	style=filled
   
   Tracker1610464494XXXadd2289459[
	label="+ add()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];

Tracker1610464494XXXdelete104431[
	label="+ delete()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];

Tracker1610464494XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];

Tracker1610464494XXXfindById104431[
	label="+ findById()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];

Tracker1610464494XXXfindByName1808118735[
	label="+ findByName()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];

Tracker1610464494XXXreplace1205812394[
	label="+ replace()"
	style=filled
	fillcolor=white
	tooltip="Tracker

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1843773104 { 
   	label=DeleteItemAction
	labeljust=l
	fillcolor=white
	style=filled
   
   DeleteItemAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="DeleteItemAction

null"
	fontcolor=darkgreen
];

DeleteItemAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="DeleteItemAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1886975866 { 
   	label=StartUI
	labeljust=l
	fillcolor=white
	style=filled
   
   StartUI1610464494XXXinit1456823761[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="StartUI

null"
	fontcolor=darkgreen
];

StartUI1610464494XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="StartUI

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_30779342 { 
   	label=CreateAction
	labeljust=l
	fillcolor=white
	style=filled
   
   CreateAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="CreateAction

null"
	fontcolor=darkgreen
];

CreateAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="CreateAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_311457233 { 
   	label=ConsoleInput
	labeljust=l
	fillcolor=white
	style=filled
   
   ConsoleInput1610464494XXXaskInt1808118735[
	label="+ askInt()"
	style=filled
	fillcolor=white
	tooltip="ConsoleInput

null"
	fontcolor=darkgreen
];

ConsoleInput1610464494XXXaskStr1808118735[
	label="+ askStr()"
	style=filled
	fillcolor=white
	tooltip="ConsoleInput

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_351412179 { 
   	label=FindByNameAction
	labeljust=l
	fillcolor=white
	style=filled
   
   FindByNameAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="FindByNameAction

null"
	fontcolor=darkgreen
];

FindByNameAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="FindByNameAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_519031755 { 
   	label=StubOutput
	labeljust=l
	fillcolor=white
	style=filled
   
   StubOutput1610464494XXXprintln1939501217[
	label="+ println()"
	style=filled
	fillcolor=white
	tooltip="StubOutput

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_629979581 { 
   	label=FindByIdAction
	labeljust=l
	fillcolor=white
	style=filled
   
   FindByIdAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="FindByIdAction

null"
	fontcolor=darkgreen
];

FindByIdAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="FindByIdAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_725758608 { 
   	label=ExitAction
	labeljust=l
	fillcolor=white
	style=filled
   
   ExitAction1610464494XXXexecute1684883782[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="ExitAction

null"
	fontcolor=darkgreen
];

ExitAction1610464494XXXname0[
	label="+ name()"
	style=filled
	fillcolor=white
	tooltip="ExitAction

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_886885572 { 
   	label=ConsoleOutput
	labeljust=l
	fillcolor=white
	style=filled
   
   ConsoleOutput1610464494XXXprintln1939501217[
	label="+ println()"
	style=filled
	fillcolor=white
	tooltip="ConsoleOutput

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_980820928 { 
   	label=StubInput
	labeljust=l
	fillcolor=white
	style=filled
   
   StubInput1610464494XXXaskInt1808118735[
	label="+ askInt()"
	style=filled
	fillcolor=white
	tooltip="StubInput

null"
	fontcolor=darkgreen
];

StubInput1610464494XXXaskStr1808118735[
	label="+ askStr()"
	style=filled
	fillcolor=white
	tooltip="StubInput

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_981896616 { 
   	label=ValidateInput
	labeljust=l
	fillcolor=white
	style=filled
   
   ValidateInput1610464494XXXaskInt1808118735[
	label="+ askInt()"
	style=filled
	fillcolor=white
	tooltip="ValidateInput

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ConsoleInput1610464494XXXaskInt1808118735 -> ConsoleInput1610464494XXXaskStr1808118735;
ConsoleInput1610464494XXXaskInt1808118735 -> ValidateInput1610464494XXXaskInt1808118735;
CreateAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXadd2289459;
DeleteItemAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXdelete104431;
EditItemAction1610464494XXXexecute1684883782 -> ConsoleInput1610464494XXXaskStr1808118735;
EditItemAction1610464494XXXexecute1684883782 -> StubInput1610464494XXXaskStr1808118735;
EditItemAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXreplace1205812394;
FindByIdAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXfindById104431;
FindByNameAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXfindByName1808118735;
ShowAllItemsAction1610464494XXXexecute1684883782 -> Tracker1610464494XXXfindAll0;
StartUI1610464494XXXinit1456823761 -> ConsoleInput1610464494XXXaskInt1808118735;
StartUI1610464494XXXinit1456823761 -> ConsoleOutput1610464494XXXprintln1939501217;
StartUI1610464494XXXinit1456823761 -> CreateAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> CreateAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> DeleteItemAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> DeleteItemAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> EditItemAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> EditItemAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> ExitAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> ExitAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> FindByIdAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> FindByIdAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> FindByNameAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> FindByNameAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> ShowAllItemsAction1610464494XXXexecute1684883782;
StartUI1610464494XXXinit1456823761 -> ShowAllItemsAction1610464494XXXname0;
StartUI1610464494XXXinit1456823761 -> StubInput1610464494XXXaskInt1808118735;
StartUI1610464494XXXinit1456823761 -> StubOutput1610464494XXXprintln1939501217;
StartUI1610464494XXXmain1859653459 -> StartUI1610464494XXXinit1456823761;
StubInput1610464494XXXaskInt1808118735 -> StubInput1610464494XXXaskStr1808118735;
    
}
@enduml